version: '3'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=str8line
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog
    ports:
    - "5432:5432"
    restart: always

  app:
    restart: always
    build: ./Blog
    working_dir: /Blog
    volumes:
    - ./Blog:/Blog
    - ~/.m2:/root/.m2
    - ./Blog/temp-dir:/workspace/temp-dir
    - ./Blog/uploads:/workspace/uploads
    ports: 
      - 80:5000
    command: mvn clean spring-boot:run
    depends_on:
    - db