var express = require('express');
var bodyParser = require('body-parser');
var app = express();
const dotenv = require('dotenv');
dotenv.config();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());
var routes = require('./routes');
app.use('/', routes);
module.exports = app;
